config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users, skip: :registrations
  root "films#index"

  resources :films do
    member do
      get 'card_en'
      get 'card_jp'
    end
  end

  resources :books do
    member do
      get 'card_en'
      get 'card_jp'
    end
  end

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable_entity'
  get '/500', to: 'errors#internal_server_error'

  match '*path', to: 'errors#not_found', via: :all
end

app/models/film.rb
class Film < ApplicationRecord
  has_and_belongs_to_many :film_tags
  belongs_to :country

  validates :title, presence: true, length: { maximum: 80 }
  validates :title_en, presence: true, length: { maximum: 80 }
  validates :comment, length: { maximum: 300 }
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  include Authenticatable
  include Authorization
  include Filterable
  include Paginatable

  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]

  def index
    set_all_tags
    set_params_tags
    @records = apply_filters(Film, filter_params, tag_type: :film_tags)

    apply_pagination(9)

    @films = @records.includes(:country, :film_tags).order(created_at: :desc)
  end

  def new
    set_all_tags
    @film = Film.new(year: 2000)
    set_film_tags
  end

  def create
    set_all_tags

    @film = Film.new(film_params)
    if @film.save
      flash[:notice] = '作成されました'
      redirect_to films_path
    else
      flash.now[:alert] = 'エラーが発生しました'
      render :new, status: :unprocessable_entity
    end

    set_film_tags
  end

  def edit
    set_all_tags

    @film = Film.find(params[:id])

    set_film_tags
  end

  def update
    set_all_tags

    @film = Film.find(params[:id])
    if @film.update(film_params)
      flash[:notice] = '更新されました'
      redirect_to session.delete(:return_to) || films_path
    else
      flash.now[:alert] = 'エラーが発生しました'
      render :edit, status: :unprocessable_entity
    end

    set_film_tags
  end

  def destroy
    @film = Film.find(params[:id])
    if @film.destroy
      flash[:notice] = '削除されました'
    else
      flash[:alert] = 'エラーが発生しました'
    end
    redirect_back(fallback_location: films_path)
  end

  def card_en
    render_card_partial(Film, 'card_en')
  end

  def card_jp
    render_card_partial(Film, 'card_jp')
  end

  private

  def authenticate_user!
    redirect_to root_path unless @is_signed
  end

  def film_params
    params.require(:film).permit(
      :title,
      :title_en,
      :comment,
      :comment_en,
      :director,
      :director_en,
      :cast,
      :cast_en,
      :review_star,
      :country_id,
      :year,
      :is_classic,
      :is_favorite
    ).merge(film_tag_ids: params[:film_tag_ids])
  end

  def filter_params
    {
      tags: @params_tags,
      is_classic: params[:is_classic] == "true",
      is_favorite: params[:is_favorite] == "true"
    }
  end

  def render_card_partial(model_class, partial_name)
    @el = model_class.find(params[:id])
    render partial: partial_name, locals: { el: @el }
  end

  def set_all_tags
    @all_tags = FilmTag.all.pluck(:label, :label_en, :id)
  end
  
  def set_params_tags
    @params_tags = params[:film_tag_ids] || []
  end

  def set_film_tags
    @film_tags = @film.film_tags.pluck(:id) || []
  end

end

app/views/films/_card_en.html.erb
<div class="card-head">
  <% if el.is_classic || el.is_favorite || el.film_tags.any? %>
    <ul class="card-tags">
      <% if el.is_classic %>
        <li class="card-tag is-classic">Classic</li>
      <% end %>
      <% if el.is_favorite %>
        <li class="card-tag is-favorite">Recommend</li>
      <% end %>
      <% el.film_tags.each do |tag| %>
        <li class="card-tag is-default"><%= tag.label_en %></li>
      <% end %>
    </ul>
  <% end %>
  <h3 class="card-title"><%= el.title_en %></h3>
</div>
<div class="card-info">
  <p class="card-star">
    <% 5.times do |i| %>
      <span class="<%= i < el.review_star.to_i && 'is-active' %>">★</span>
    <% end %>
  </p>
  <p class="card-when-where"><%= el.year %>/<%= el.country.label_en %></p>
</div>
<% if el.comment_en.present? %><p class="card-body"><%= el.comment_en %></p><% end %>
<% if el.director_en.present? || el.cast_en.present? %>
  <details class="card-details">
    <summary class="toggle-more"><span class="toggle-more-close">Close</span><span class="toggle-more-open">Open</span></summary>
    <dl class="card-info-dl">
      <% if el.director_en.present? %>
        <dt class="card-info-dt">Directer</dt>
        <dd class="card-info-dd"><%= el.director_en %></dd>
      <% end %>

      <% if el.cast_en.present? %>
        <dt class="card-info-dt">Cast</dt>
        <dd class="card-info-dd"><%= el.cast_en %></dd>
      <% end %>
    </dl>
  </details>
<% end %>

app/views/films/_card_jp.html.erb
<div class="card-head">
  <% if el.is_classic || el.is_favorite || el.film_tags.any? %>
    <ul class="card-tags">
      <% if el.is_classic %>
        <li class="card-tag is-classic">名作</li>
      <% end %>
      <% if el.is_favorite %>
        <li class="card-tag is-favorite">おすすめ</li>
      <% end %>
      <% el.film_tags.each do |tag| %>
        <li class="card-tag is-default"><%= tag.label %></li>
      <% end %>
    </ul>
  <% end %>
  <h3 class="card-title"><%= el.title %></h3>
</div>
<div class="card-info">
  <p class="card-star">
    <% 5.times do |i| %>
      <span class="<%= i < el.review_star.to_i && 'is-active' %>">★</span>
    <% end %>
  </p>
  <p class="card-when-where"><%= el.year %>/<%= el.country.label %></p>
</div>
<% if el.comment.present? %><p class="card-body"><%= el.comment %></p><% end %>
<% if el.director.present? || el.cast.present? %>
  <details class="card-details">
    <summary class="toggle-more"><span class="toggle-more-close">閉じる</span><span class="toggle-more-open">開く</span></summary>
    <dl class="card-info-dl">
      <% if el.director.present? %>
        <dt class="card-info-dt">監督</dt>
        <dd class="card-info-dd"><%= el.director %></dd>
      <% end %>
    
      <% if el.cast.present? %>
        <dt class="card-info-dt">キャスト</dt>
        <dd class="card-info-dd"><%= el.cast %></dd>
      <% end %>
    </dl>
  </details>
<% end %>
<% if @is_signed %>
  <div class="card-controller">
    <%= button_to film_path(el.id), method: :delete, class: 'card-delete cursor-pointer hover:bg-circle', onclick: "return confirm('本当に削除しますか？');" do %>
      <%= image_tag("icon-trash.svg", alt: "Cosmic Library", width: 24, height: 24) %>
    <% end %>
    <%= link_to edit_film_path(el.id), class: 'card-edit cursor-pointer hover:bg-circle' do %>
      <%= image_tag("icon-edit.svg", alt: "Cosmic Library", width: 24, height: 24) %>
    <% end %>
    <label class="form-switch">
      <input type="checkbox" name="">
      <span class="form-switch-ball"></span>
    </label>
  </div>
<% end %>

app/views/films/_form.html.erb
<%= form_with model: @film, html: { class: "form max-w-157" }  do |f| %>
  <%= render partial: 'partials/form_review_star', locals: { f: f, review_star: @film.review_star } %>
  <div class="form-items mt-14">
    <%= f.label :title, "タイトル", class: "form-required" do %>
      <%= f.text_field :title, class: "form-input", placeholder: "タイトルを入力してください", required: true %>
    <% end %>
    <%= f.label :title_en, "タイトル（英語）", class: "form-required form-item-en" do %>
      <%= f.text_field :title_en, class: "form-input", placeholder: "タイトル（英語）を入力してください", required: true %>
    <% end %>
    <div class="flex gap-3 max-w-82">
      <%= f.select :country_id, options_from_collection_for_select(Country.all, :id, :label, @film.country_id), {}, class: "form-select" %>
      <%= f.number_field :year, class: "form-input" %>
    </div>
    <%= f.label :comment, "コメント" do %>
      <%= f.text_field :comment, class: "form-textarea", maxlength: 100, placeholder: "コメントを入力してください" %>
    <% end %>
    <%= f.label :comment_en, "コメント（英語）", class: "form-item-en" do %>
      <%= f.text_field :comment_en, class: "form-textarea", maxlength: 100, placeholder: "コメント（英語）を入力してください" %>
    <% end %>
    <%= f.label :director, "監督名", class: "form-required" do %>
      <%= f.text_field :director, class: "form-input", placeholder: "監督名を入力してください", required: true %>
    <% end %>
    <%= f.label :director_en, "監督名（英語）", class: "form-required form-item-en" do %>
      <%= f.text_field :director_en, class: "form-input", placeholder: "監督名（英語）を入力してください", required: true %>
    <% end %>
    <%= f.label :cast, "キャスト" do %>
      <%= f.text_field :cast, class: "form-input", placeholder: "キャストを入力してください" %>
    <% end %>
    <%= f.label :cast_en, "キャスト（英語）", class: "form-item-en" do %>
      <%= f.text_field :cast_en, class: "form-input", placeholder: "キャスト（英語）を入力してください" %>
    <% end %>
  </div>
  <p class="form-memo">左上の●は入力必須です</p>

  <div class="mt-6">
    <div class="sort-chips">
      <label class="sort-chip-label">
        <%= f.check_box :is_classic %>
        <span class="sort-chip-txt">名作</span>
      </label>
      <label class="sort-chip-label">
        <%= f.check_box :is_favorite %>
        <span class="sort-chip-txt">おすすめ</span>
      </label>
      <% @all_tags.each do |tag| %>
        <label class="sort-chip-label">
          <input type="checkbox" name="film_tag_ids[]" value="<%= tag[2] %>" <%= @film_tags.include?(tag[2]) ? "checked" : "" %>>
          <span class="sort-chip-txt"><%= tag[0] %></span>
        </label>
      <% end %>
    </div>
  </div>


  <div class="flex gap-3 mt-10">
    <%= f.submit @film.new_record? ? "作成する" : "保存する", class: "form-btn" %>
    <%= link_to "キャンセル", :back, class: "form-btn is-cancel" %>
  </div>
<% end %>

app/views/films/edit.html.erb
<section>
  <%= render partial: 'partials/form_head', locals: { heading: "更新" } %>
  <%= render "form" %>
</section>

app/views/films/index.html.erb
<%= render 'partials/flash_messages' %>
<% if @films.present? %>
<main class="cards">
  <% @films.each_with_index do |el, i| %>
    <article class='card card#{i + 1}' data-controller="toggle-card" data-model-id="<%= el.id %>" data-model-type="film">
      <div class='card-wrap' data-toggle-card-target="content">
        <%= render partial: 'card_jp', locals: { el: el } %>
      </div>
      <% unless @is_signed %>
        <button data-action="click->toggle-card#toggleCardType" class="card-translate btn-translate">
          <%= image_tag("icon-translate.svg", alt: "翻訳する", width: 40, height: 40, class: "btn-translate-img") %>
        </button>
      <% end %>
    </article>
  <% end %>
</main>
<% else %>
<div class="no-article">
  <p class="no-article-text"><span>作</span><span>品</span><span>が</span><span>見</span><span>つ</span><span>か</span><span>り</span><span>ま</span><span>せ</span><span>ん</span><span>で</span><span>し</span><span>た</span></p>
</div>
<% end %>
<aside class="sort" data-controller="toggle-lang">
  <div class="sort-translate">
    <button data-action="click->toggle-lang#toggleLang" class="btn-translate">
      <%= image_tag("icon-translate.svg", alt: "翻訳する", width: 40, height: 40, class: "btn-translate-img") %>
    </button>
  </div>
  <div data-toggle-lang-target="contentJp">
    <%= render partial: 'partials/filter', locals: {
      url: films_path,
      classic_label: "名作",
      favorite_label: "おすすめ",
      tag_name: "film_tag_ids[]",
      tag_label_index: 0,
      submit_text: "絞り込み"
    } %>
    <%= render partial: 'partials/pagy_nav', locals: {
      count_text: "全 #{@page_total} 件",
    } %>
  </div>

  <div data-toggle-lang-target="contentEn" class="hidden">
    <%= render partial: 'partials/filter', locals: {
      url: films_path,
      classic_label: "Classic",
      favorite_label: "Recommend",
      tag_name: "film_tag_ids[]",
      tag_label_index: 1,
      submit_text: "Filter"
    } %>
    <%= render partial: 'partials/pagy_nav', locals: {
      count_text: "All #{@page_total} items",
    } %>
  </div>
</aside>
<% if @is_signed %>
  <%= link_to new_film_path, class: "create-btn" do %>
    <%= image_tag asset_path('icon-plus.svg'), alt: "作成する", width: 24, height: 24 %>
  <% end %>
<% end %>

app/views/films/new.html.erb
<section>
  <%= render partial: 'partials/form_head', locals: { heading: "作成" } %>
  <%= render "form" %>
</section>