config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users, skip: :registrations
  root "films#index"

  resources :films do
    member do
      get 'card_en'
      get 'card_jp'
    end
  end

  resources :books do
    member do
      get 'card_en'
      get 'card_jp'
    end
  end

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable_entity'
  get '/500', to: 'errors#internal_server_error'

  match '*path', to: 'errors#not_found', via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-JYYHNP01YF"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-JYYHNP01YF');
    </script>
    <title>Cosmic Library</title>
    <meta name="description" content="「Cosmic Library」は、わたしがこれまでに読んだ本や観た映画を記録し、共有できるWEBアプリケーションです。これから出会う作品の無限の可能性と宇宙の無限の広がりが重なるようにデザインしました。">
    <link rel="canonical" href="https://cosmic-library.lolipop.io" />
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="theme-color" content="#0B0F2B">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta property="og:title" content="Cosmic Library">
    <meta property="og:description" content="「Cosmic Library」は、わたしがこれまでに読んだ本や観た映画を記録し、共有できるWEBアプリケーションです。これから出会う作品の無限の可能性と宇宙の無限の広がりが重なるようにデザインしました。">
    <meta property="og:image" content="<%= asset_path('ogp.gif') %>">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class='<%= @is_modal_open ? "is-modal-open" : "" %>'>
    <div class="l-container l-inner-md">

      <header class="hd">
        <%=link_to root_path, class: "inline-block" do %>
         <img src="<%= asset_path('logo-anime.svg') %>" alt="Cosmic Library" width="177" height="106" class="hd-logo-img" />
        <% end %>
      </header>

      <nav class="pagenav">
        <ul class="pagenav-list">
          <li class="pagenav-item">
            <%= link_to "Films", root_path, class: "pagenav-anc #{'is-active' if request.path == '/' || request.path.start_with?('/films')}" %>
          </li>
          <li class="pagenav-item">
            <%= link_to "Books", books_path, class: "pagenav-anc #{'is-active' if request.path.start_with?('/books')}" %>
          </li>
        </ul>
      </nav>

      <div class="l-main">
        <%= yield %>
      </div>

      <nav class="helpnav">
        <ul class="helpnav-list">
          <li class="helpnav-item"><%= link_to "GitHub", "https://github.com/Paglinawan/cosmic-library", class: "helpnav-anc", target: "_blank" %></li>
          <% if @is_signed %>
            <li class="helpnav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "helpnav-anc" %></li>
          <% else %>
            <li class="helpnav-item"><%= link_to "SignIn", new_user_session_path, class: "helpnav-anc" %></li>
          <% end %>
        </ul>
        <% if !@is_signed_owner and @is_signed %>
          <p class="helpnav-login-status">オーナーアカウントではありません</p>
        <% end %>
      </nav>

      <footer class="ft">
        <p class="ft-copyright">&copy; 2024 Paglinawan</p>
      </footer>

    </div>
  
  </body>
</html>